version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0

cache_key: &cache_key awesome-20230530-{{ checksum "go.sum" }}

executors:
  docker-go:
    docker:
        - image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/cimg-go:1.25-build
          aws_auth:
            oidc_role_arn: ${AWS_IAM_ROLE}
commands:
  cache-setup:
    steps:
      - restore_cache:
          name: Restore dep cache
          keys: 
            - *cache_key 
      - save_cache:
          name: Save dep cache 
          key: *cache_key
          paths: 
            - ~/go/pkg
  lint-test:
    steps:
      - run:
          name: Run linter
          command: make lint
      - aws-cli/setup:
          role_arn: arn:aws:iam::651264383976:role/buildit/circle-role
          role_session_name: awesome-tests
      - run: 
          name: test aws cli status
          command: aws sts get-caller-identity
      - run: 
          name: test aws cli status
          command: echo ${AWS_CREDS_PROVIDER_TEST_ASSUME_ROLE}
      - run:
          name: Run test
          command: go test ./...
  codegen: 
    steps:
      - run: 
          name: Run go generate
          command: go generate ./codegen/codegen.go
  build:
    steps: 
      - run: 
          name: Build code 
          command: make build

jobs:
  lint-build-test:
    executor: docker-go
    steps:
      - aws-cli/setup:
          role_arn: arn:aws:iam::651264383976:role/buildit/circle-role
          role_session_name: awesome-tests
      - checkout 
      - cache-setup
      - lint-test 
      - codegen
      - build
  release:
    executor: docker-go
    steps:
      - checkout 
      - run: 
          name: Tag release in github
          command: |
            .circleci/tagger.sh
      - run:
          name: cut release in github with goreleaser
          command: goreleaser release -f .circleci/goreleaser.yml
workflows:
  build-test-release:
    jobs:
     - lint-build-test:
         context: org-global 
     - release:
         context: org-global
         requires:
           - lint-build-test
         filters:
           branches:
             only:
               - master
